name: Deployment
on:
  push:
    branches:
      - 'main'
      - 'ci-cd'
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ vars.PORT }}
          script: |
            cd
            rm -rf Free2Learn-Frontend
            git clone git@github.com:Free2Learn-Capstone/Free2Learn-Frontend.git
            cd Free2Learn-Frontend
            npm i
            npm run build
            pm2 stop next
            pm2 start npm --name "next" -- start