name: Deployment
on:
  push:
    branches:
      - 'main'
      - 'ci-cd'
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      # 1. Connect via SSH to EC2 instance
      - name: Test commands
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.HOST }}
          username: ${{ vars.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ vars.PORT }}
          script: |
            whoami
            ls -al
      # 2. Download repo or copy project files
      # 3. Build next project
      # 4. Run next project with pm2